# Generated by Django 5.0.7 on 2024-07-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cutie',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
